version: '3.9'

services:
  wibi-backend1:
    build: .
    env_file: .env
    ports:
      - "5001:5000"   # optional for testing outside Nginx
    restart: always

  wibi-backend2:
    build: .
    env_file: .env
    ports:
      - "5002:5000"   # optional for testing outside Nginx
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - wibi-backend1
      - wibi-backend2
    restart: always

